### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Artyom-rgb** [elkowar/eww#192]
## Describe the bug
the widget is always on top of all windows

## Reproducing the issue
`  <windows>
    
	      <window name="main_window">
      <geometry x="60%" y="10%" width="45%" height="40%"/> 
      <widget>
        <clock/> 
      </widget>
    </window>
  </windows>`
## Expected behaviour
I want the widget to be only on the desktop

## Additional context
![image](https://user-images.githubusercontent.com/72004410/121789646-2e031980-cbe0-11eb-95a7-6194356b499a.png)
![image](https://user-images.githubusercontent.com/72004410/121789735-14160680-cbe1-11eb-9549-89dca4973c22.png)

**Comment by undefinedDarkness** [comment]
Play around with the focusable attribute
Stacking bg doesn't work 9 times out of 10 because X11 is a big mess

**Comment by Artyom-rgb** [comment]
When I do focusable= "true", my widget turns into a separate window, which then opens and closes
![image](https://user-images.githubusercontent.com/72004410/121799882-6f72e380-cc37-11eb-9630-e9b67d0e679f.png)

**Comment by undefinedDarkness** [comment]
Yeah, youll need to exclude it somehow
Eww needs to do this atm maybe a fix will be found in the future

**Comment by Artyom-rgb** [comment]
okay thanks

**Comment by eq0** [comment]
same here..

**Comment by nodgear** [comment]
Same issue for me, using Openbox on Arch

**Comment by elkowar** [comment]
This should most likely be fixed by https://github.com/elkowar/eww/pull/217 which allows some more control over how the windows are reported to the WM. That PR will most likely just be included with the config rework though, not much point in merging it on it's own right now,.... But for those that want it now, maybe check out that PR and try if the new options provided there allow to fix this

**Comment by gordnhoo** [comment]
I have this exact same issue when will this be solved?

**Comment by RossComputerGuy** [comment]
I'm having the same problem with i3.

**Comment by beyonson** [comment]
i also have this bug

**Comment by clxxiii** [comment]
This is still an issue in i3, no combination of window properties I've found allows a widget to be underneath a tiled window

**Comment by dacid44** [comment]
Also having this issue in Cinnamon (arch). In addition `:wm-ignore false` causes one of my monitors to not be able to have any windows on it for some reason (though glava stays).

**Comment by Polanas** [comment]
Yep, same issue on arch, X11 and i3

**Comment by PouPeuu** [comment]
Still have this issue on arch, X11, and i3

**Comment by daraem** [comment]
still have this issue on ubuntu, X11, i3
